language: python
python: 
    - "3.6"
    - "3.7"
install:
    - pip install -r ml-service/ml-server/requirements.txt
script:
    - python -m pytest
    - cd frontend/view
    - npm run build
    - npm run test
